# Generated by Django 3.2 on 2022-11-15 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(choices=[('IT', 'IT'), ('Management', 'Менеджмент'), ('Audit', 'Аудит'), ('HR', 'HR')], verbose_name='Категория вакансии')),
                ('about', models.TextField(max_length=500, verbose_name='О себе')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Желаемая зарплата')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Последние изменение')),
                ('is_active', models.BooleanField(default=False, verbose_name='Скрыть резюме')),
                ('telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на телеграм')),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на Linkedin')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на Facebook')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Соискатель')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Обязанности')),
                ('company', models.CharField(max_length=100, verbose_name='Название компании')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Начал работать')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Закончил работать')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study', models.CharField(max_length=100, verbose_name='Место обучения')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Начал обучаться')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Закончил обучаться')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.resume')),
            ],
        ),
    ]
