# Generated by Django 3.2 on 2022-11-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название вакансии')),
                ('salary', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Заработная плата')),
                ('description', models.TextField(max_length=3000, verbose_name='Описание вакансии')),
                ('experience', models.FloatField(verbose_name='Опыт работы')),
                ('category', models.TextField(choices=[('IT', 'IT'), ('DESIGN', 'Дизайн'), ('MANAGEMENT', 'Менеджмент'), ('MEDICINE', 'Медицина'), ('ENGINEERING', 'Инженерное дело'), ('ART', 'Искусство'), ('TRANSPORT', 'Транспорт'), ('MARKETING', 'Маркетинг'), ('TRADE', 'Торговля'), ('ECONOMY', 'Экономика')], default='IT', verbose_name='Категория вакансии')),
            ],
        ),
    ]
