# Generated by Django 3.2 on 2022-11-16 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='applicant',
            new_name='author',
        ),
    ]
