# Generated by Django 3.2 on 2022-11-19 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_resume_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='about',
            field=models.TextField(max_length=3000, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='category',
            field=models.TextField(blank=True, choices=[('IT', 'IT'), ('DESIGN', 'Дизайн'), ('MANAGEMENT', 'Менеджмент'), ('MEDICINE', 'Медицина'), ('ENGINEERING', 'Инженерное дело'), ('ART', 'Искусство'), ('TRANSPORT', 'Транспорт'), ('MARKETING', 'Маркетинг'), ('TRADE', 'Торговля'), ('ECONOMY', 'Экономика')], null=True, verbose_name='Категория вакансии'),
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название вакансии')),
                ('salary', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Заработная плата')),
                ('description', models.TextField(max_length=3000, verbose_name='Описание вакансии')),
                ('experience', models.FloatField(verbose_name='Опыт работы')),
                ('category', models.TextField(choices=[('IT', 'IT'), ('DESIGN', 'Дизайн'), ('MANAGEMENT', 'Менеджмент'), ('MEDICINE', 'Медицина'), ('ENGINEERING', 'Инженерное дело'), ('ART', 'Искусство'), ('TRANSPORT', 'Транспорт'), ('MARKETING', 'Маркетинг'), ('TRADE', 'Торговля'), ('ECONOMY', 'Экономика')], verbose_name='Категория вакансии')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Работодатель')),
            ],
        ),
    ]
