# Generated by Django 3.2 on 2022-11-19 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_alter_vacancy_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='author',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancy', to=settings.AUTH_USER_MODEL, verbose_name='Автор вакансии'),
        ),
    ]
