# Generated by Django 3.2 on 2022-11-19 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_vacancy_employer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='employer',
        ),
    ]
