# Generated by Django 3.2 on 2022-11-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_vacancy_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Заработная плата'),
        ),
    ]
