# Generated by Django 3.2 on 2022-11-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='/default_av.jpg', null=True, upload_to='avatars', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_role',
            field=models.TextField(choices=[('Employer', 'Работодатель'), ('Employee', 'Соискатель')], verbose_name='Роль'),
        ),
    ]
